vversion: "3"

services:
  # PostgreSQL database
  db:
    image: postgres:15
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgAdmin web UI
  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  # Next.js app using Yarn
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    command: ["yarn", "dev"]  # hot-reload for development
    #COMMAND: [ "pm2-runtime", "start", "npm", "--", "start" ]\

volumes:
  pgdata:

